steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app:$COMMIT_SHA'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'catch-me-if-you-can'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--allow-unauthenticated=false'
      - '--session-affinity'
      - '--timeout'
      - '300'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app:$COMMIT_SHA'
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/catch-me-if-you-can/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
